name: Release Mozeidon App

on:
  push:
    # run only against tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Release Folder
        run: cd release && zip -r ../mozeidon-${{ github.ref_name }}.zip mozeidon
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mozeidon-${{ github.ref_name }}.zip
